### ISSUE TITLE
Publish a new version?

### ISSUE THREAD

**Issue by fzyzcjy** [sunshine-protocol/allo-isolate#13]
Hi thanks for this lib! It has been days since some PRs I made ;) So I wonder when will we have the new version? Seems that I cannot use the git dependency, otherwise the following error happens when publishing to crate:

> error: all dependencies must have a version specified when publishing.
dependency `allo-isolate` does not specify a version
Note: The published dependency will use the version from crates.io,
the `git` specification will be removed from the dependency declaration.

**Comment by fzyzcjy** [comment]
Oops I forget to @ people: @shekohex @jerel

**Comment by shekohex** [comment]
Released `v0.1.10` 🎉

**Comment by fzyzcjy** [comment]
🎉
