### ISSUE TITLE
Support `Float32List`? (Can make a PR)

### ISSUE THREAD

**Issue by fzyzcjy** [sunshine-protocol/allo-isolate#14]
I need Float32List for things like `drawRawAtlas`; I can make a PR for this.

**Comment by shekohex** [comment]
We do have implementation for both `f32` and `f64` already so `Vec<f32>` should work, no?

Are the `Float32List` is different than `List<double>` in dart? 

if so, we could implement the missing typed dart values too.

Would be great to see a PR for that.

**Comment by fzyzcjy** [comment]
> Are the Float32List is different than List<double> in dart?

Yes, very different. The former is much faster and memory-efficient than the latter. In addition, we can create a zero-copy Float32List while we cannot for the latter.

> Would be great to see a PR for that.

#15 ;)

**Comment by fzyzcjy** [comment]
btw  even Float64List is much better than List of double. See dart/flutter's doc for more details.

**Comment by shekohex** [comment]
Closed from #15 and now available with `v0.1.11`.

Thank you!

**Comment by fzyzcjy** [comment]
You are welcome!
