### ISSUE TITLE
The official website, Sunshine.foundation, says that domain is being sold...

### ISSUE THREAD

**Issue by fzyzcjy** [sunshine-protocol/allo-isolate#4]
Hi when looking around, I see the official website linked from here https://github.com/sunshine-protocol. But it says it is being sold. So maybe the link needs to be updated ;)

![image](https://user-images.githubusercontent.com/5236035/135022628-5031609a-a4f1-4527-b6ef-e4d8a60fd12c.png)

**Comment by shekohex** [comment]
Yea! I guess the development of the project is halted for now, but I'm still actively maintaining the other repos.

> Closing as it is really relevant right now.

**Comment by fzyzcjy** [comment]
@shekohex So may I know what sunshine foundation (or you) are doing? I am curious about it ;)

**Comment by shekohex** [comment]
You can read more about Sunshine here: https://dev.to/sunshine-chain/introducing-sunshine-2o53
